### ISSUE TITLE
Definitions of done! 😊

### ISSUE THREAD

**Issue by Nazneen05x** [Demivdm/connect-your-tribe-profile-card#4]
**- Is het eindresultaat gedocumenteerd in wiki aan de hand van de DLC?** 
       Wiki moet je nog aanzetten! 😊
**- Is het kaartje gepubliceerd via cyclic.sh?** 
Echt een leuke url naam hihi
**- Gebruik het kaartje gegevens uit de rest api op whois.fdnd.nl** 
Goed gedaan! misschien volgende keer kijk of je meer data (api) kan implementeren in je visitekaartje😊. 
**- Is het visitekaartje gemaakt met node?**
Je hebt wat errors in je bestand. Je mag geen ul, headers en p in een span doen.
<img width="1403" alt="Schermafbeelding 2023-02-10 om 10 26 34" src="https://user-images.githubusercontent.com/112861261/218055095-ceec8050-befc-4441-9552-f3dd84e564ef.png">

**Comment by Demivdm** [comment]
Ik heb de span verwijderd! Ik zal kijken of ik bij de about nog meer data kan implementeren.

https://github.com/Demivdm/connect-your-tribe-profile-card/commit/29d001c42c7ee90ab5ea06eef0b92455530bbb4b
