### ISSUE TITLE
Verplaatsen van variabelen

### ISSUE THREAD

**Issue by ju5tu5** [Demivdm/connect-your-tribe-profile-card#5]
https://github.com/Demivdm/connect-your-tribe-profile-card/blob/fd0052688498f44993e1fbf539f33cce2cb0a650/index.js#L14-L16

Hi! Deze kan je beter bovenin vlak na de imports neerzetten.. dus op ~regel 3.

**Comment by Demivdm** [comment]
Thanks! Ik heb ze verplaatst :)

https://github.com/Demivdm/connect-your-tribe-profile-card/commit/86eef6967b43c803104f5e53551a7cc195fb027d
